"use client";

import Link from "next/link";
import { ArrowUpRight, Check, CircleAlert, FolderKanban, PlayCircle, Search } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { api, type Finding, type Plan, type Project, type Run } from "@/lib/api";

export default function Projects() {
  const [projects, setProjects] = useState<Project[]>([]);
  const [runs, setRuns] = useState<Run[]>([]);
  const [plans, setPlans] = useState<Plan[]>([]);
  const [findings, setFindings] = useState<Finding[]>([]);
  const [query, setQuery] = useState("");
  const [error, setError] = useState("");
  useEffect(() => { Promise.all([api<{projects:Project[]}>('/projects'), api<{runs:Run[]}>('/runs'), api<{plans:Plan[]}>('/plans'), api<{findings:Finding[]}>('/findings')]).then(([p,r,pl,f]) => { setProjects(p.projects); setRuns(r.runs); setPlans(pl.plans); setFindings(f.findings); }).catch((e) => setError(e.message)); }, []);
  const visible = useMemo(() => projects.filter((p) => `${p.project_name} ${p.workspace_root}`.toLowerCase().includes(query.toLowerCase())), [projects, query]);
  const active = runs.find((r) => r.status === "RUNNING" || r.status === "QUEUED");
  const failed = runs.filter((r) => r.status === "FAIL" || r.status === "BLOCKED").length;
  return <main className="dashboard">
    <section className="dashboard-heading"><div><div className="eyebrow">Quality command / workspace index</div><h1>PROJECTS</h1><p className="muted">Every quality decision starts with a target, a snapshot, and a testable change.</p></div><div className="actions"><Link className="button primary inline-flex items-center gap-1.5" href="/projects/new">Initialize workspace <ArrowUpRight className="size-3.5" aria-hidden="true" /></Link><Link className="button secondary" href="/assistant">Ask HoloQA</Link></div></section>
    {error && <div className="callout section">{error}</div>}
    <section className="kpi-grid"><div className="kpi"><span className="kpi-icon"><FolderKanban aria-hidden="true" /></span><div><span className="label">Workspaces</span><strong>{projects.length}</strong><span className="trend up inline-flex items-center gap-1"><ArrowUpRight className="size-3" aria-hidden="true" /> indexed targets</span></div></div><div className="kpi"><span className="kpi-icon"><PlayCircle aria-hidden="true" /></span><div><span className="label">Runs</span><strong>{runs.length}</strong><span className="trend inline-flex items-center gap-1">{active ? <><span className="status running"><i /></span> execution active</> : "workers idle"}</span></div></div><div className="kpi"><span className="kpi-icon"><CircleAlert aria-hidden="true" /></span><div><span className="label">Attention</span><strong className="accent-text">{failed + findings.filter((f) => f.state !== "closed").length}</strong><span className="trend alert">failures + open findings</span></div></div><div className="kpi"><span className="kpi-icon"><Check aria-hidden="true" /></span><div><span className="label">Approved plans</span><strong>{plans.filter((p) => p.approved).length}</strong><span className="trend">{plans.length} total drafts</span></div></div></section>
    <section className="dashboard-grid"><div className="dashboard-panel projects-panel"><div className="panel-heading"><h2>Workspace registry</h2><label className="search"><Search className="size-4" aria-hidden="true" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Filter projects..." aria-label="Filter projects" /></label></div><div className="project-list"><div className="project-row header"><span>Project</span><span>Snapshot</span><span>Runs</span><span>Quality</span><span /></div>{visible.map((p, i) => { const pruns = runs.filter((r) => r.plan_id && plans.find((pl) => pl.plan_id === r.plan_id)?.project_id === p.project_id); const open = findings.filter((f) => f.state !== "closed" && pruns.some((r) => r.run_id === f.run_id)).length; return <div className="project-row" key={p.project_id}><span><strong>{p.project_name}</strong><small className="mono muted">{p.workspace_root}</small></span><span className="mono">{p.codegraph_status || "snapshot ready"}</span><span className="mono">{pruns.length} runs</span><span className={`status ${open ? "fail" : "pass"}`}><i />{open ? `${open} attention` : "READY"}</span><Link className="link inline-flex items-center gap-1" href={`/projects/${p.project_id}`}>Open <ArrowUpRight className="size-3" aria-hidden="true" /></Link></div>; })}{!visible.length && <div className="empty">No workspaces match this filter.</div>}</div></div><div className="dashboard-panel activity-panel"><div className="panel-heading"><h2>Activity feed</h2><Link className="link mono inline-flex items-center gap-1" href="/runs">All runs <ArrowUpRight className="size-3" aria-hidden="true" /></Link></div><div className="timeline">{runs.slice(0, 6).map((r, i) => <div className="activity" key={r.run_id}><span className={`timeline-dot ${i === 0 ? "hot" : ""}`} /><div><strong>{r.status === "RUNNING" ? "Agent is executing" : `Run ${r.status.toLowerCase()}`}</strong><small className="mono">{r.run_id} · {r.current_test_id || r.message}</small></div><time>{r.finished_at ? new Date(r.finished_at).toLocaleDateString() : "now"}</time></div>)}{!runs.length && <div className="empty">Execution activity will appear here.</div>}</div></div></section>
    <section className="lower-grid"><div className="dashboard-panel"><div className="panel-heading"><h2>Launchpad</h2></div><div className="panel-links"><Link href="/projects/demo/tests">Author a test plan <span className="inline-flex items-center gap-1">01 <ArrowUpRight className="size-3" aria-hidden="true" /></span></Link><Link href="/requirements">Map requirements <span className="inline-flex items-center gap-1">02 <ArrowUpRight className="size-3" aria-hidden="true" /></span></Link><Link href="/reports">Prepare release report <span className="inline-flex items-center gap-1">03 <ArrowUpRight className="size-3" aria-hidden="true" /></span></Link></div></div><div className="dashboard-panel"><div className="panel-heading"><h2>Quality pulse</h2></div><div className="health-content"><div className="donut"><span>{runs.length ? Math.round((runs.filter((r) => r.status === "PASS").length / runs.length) * 100) : 0}<small>PASS RATE</small></span></div><div className="legend"><div><i className="healthy" /><span>Passed</span><b>{runs.filter((r) => r.status === "PASS").length}</b><em>runs</em></div><div><i className="attention" /><span>Attention</span><b>{failed}</b><em>runs</em></div><div><i className="idle" /><span>Queued</span><b>{runs.filter((r) => r.status === "QUEUED").length}</b><em>runs</em></div></div></div></div><div className="dashboard-panel"><div className="panel-heading"><h2>Next decision</h2></div><div className="panel-copy"><div className="eyebrow">{active ? "LIVE EXECUTION" : failed ? "TRIAGE QUEUE" : "READY TO SHIP"}</div><h3>{active ? active.run_id : failed ? `${failed} runs need review` : "No blockers detected"}</h3><p className="muted">{active ? active.current_step || "Agent is preparing the next action." : failed ? "Open the finding ledger and turn evidence into a retest." : "Create an approved plan to put the browser worker to work."}</p><Link className="link mono inline-flex items-center gap-1" href={active ? `/runs/${active.run_id}` : failed ? "/findings" : "/projects/demo/tests"}>{active ? "Watch live run" : failed ? "Open findings" : "Open Test Studio"} <ArrowUpRight className="size-3" aria-hidden="true" /></Link></div></div></section>
  </main>;
}
