'use client'
import { use, useEffect, useState } from 'react'
import { api, type Environment } from '@/lib/api'
import { FeaturePage } from '@/components/feature-page'

export default function Environments({params}:{params:Promise<{projectId:string}>}) {
  const projectId = use(params).projectId
  const [items,setItems] = useState<Environment[]>([]); const [form,setForm] = useState({name:'Staging',base_url:'http://localhost:3000',kind:'staging',browser:'chromium',viewport:'1440x900'}); const [message,setMessage] = useState('')
  const load = () => api<{environments:Environment[]}>(`/environments?project_id=${projectId}`).then(x=>setItems(x.environments)).catch(e=>setMessage(e.message))
  useEffect(()=>{load()},[projectId])
  async function create(e:React.FormEvent){e.preventDefault(); try { await api('/environments',{method:'POST',body:JSON.stringify({...form,project_id:projectId})}); setMessage('Environment saved.'); setForm({...form,name:'',base_url:''}); load() } catch(e){setMessage((e as Error).message)} }
  async function remove(id:string){await api(`/environments/${id}`,{method:'DELETE'});load()}
  return <FeaturePage eyebrow={`Target management / ${projectId}`} title="ENVIRONMENTS" intro="Named destinations keep execution safe, repeatable, and ready for browser profiles."><section className="section grid-2"><form className="panel" onSubmit={create}><div className="eyebrow">Register target</div><h3>New environment</h3><div className="field"><label>Name</label><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Release candidate"/></div><div className="field"><label>Base URL</label><input required type="url" value={form.base_url} onChange={e=>setForm({...form,base_url:e.target.value})}/></div><div className="grid-2"><div className="field"><label>Kind</label><select value={form.kind} onChange={e=>setForm({...form,kind:e.target.value})}><option>local</option><option>staging</option><option>uat</option><option>production</option></select></div><div className="field"><label>Browser</label><select value={form.browser} onChange={e=>setForm({...form,browser:e.target.value})}><option value="chromium">Chrome / Chromium</option><option value="firefox">Firefox</option><option value="webkit">WebKit</option></select></div></div><div className="field"><label>Viewport</label><select value={form.viewport} onChange={e=>setForm({...form,viewport:e.target.value})}><option>1440x900</option><option>390x844</option><option>768x1024</option></select></div><button className="button primary">Save environment ↗</button><p className="muted">{message}</p></form><div className="panel"><div className="eyebrow">Execution policy</div><h3>Protected by default</h3><p className="muted">Plans still require approval. Environment records only define where the approved browser worker may run.</p><div className="callout mono">SECRETS / NEVER RETURNED TO THE BROWSER</div><div className="field" style={{marginTop:18}}><label>Profiles ready next</label><div className="mono">auth cookies · locale · timezone · network</div></div></div></section><section className="section"><div className="section-head"><div><div className="eyebrow">Registered destinations</div><h2>Target catalog</h2></div></div><div className="grid-3">{items.map(env=><div className="panel" key={env.environment_id}><div className="eyebrow">{env.kind} · {env.browser}</div><h3>{env.name}</h3><div className="mono muted">{env.base_url}</div><p className="muted">{env.viewport} · {env.locale}</p><button className="button secondary" onClick={()=>remove(env.environment_id)}>Remove</button></div>)}{!items.length&&<div className="empty">No environments yet. Register the first safe target above.</div>}</div></section></FeaturePage>
}
