'use client'

import Link from 'next/link'
import { ArrowUpRight, CheckCircle2, CircleDot, Copy, Server, TerminalSquare } from 'lucide-react'
import { useState } from 'react'
import { FeaturePage } from '@/components/feature-page'

const defaultEndpoint = 'http://localhost:8100/mcp'
const promptsFor = (endpoint: string) => [
  `You are my AI coding agent. Connect to HoloQA using the remote Streamable HTTP MCP endpoint: ${endpoint}\n\nFirst inspect the live MCP tool catalog. If HoloQA tools are already available, report the namespace and stop. If they are missing, do not run uv, Docker, Playwright, or any local MCP process. Tell me that HoloQA is not configured and ask exactly: “May I add the remote HoloQA MCP server at ${endpoint} to this client and reload MCP?”\n\nWait for my explicit confirmation. Do not edit MCP configuration, add a server, or reload anything before I confirm. After confirmation, add this remote Streamable HTTP server, reload MCP, and verify that holoqa_project_inspect and holoqa_open_run_session are available. If this client cannot edit its own MCP settings, show me the exact server URL and tell me where to add it, then wait for me to reload.`,
  `You are my AI coding agent. Initialize the application in HoloQA.\n\nUse the connected remote HoloQA MCP server. The application must already be mounted on that server under /workspace/<workspace-id>.\n1. Call holoqa_project_inspect with the server-side workspace path.\n2. Call holoqa_initialize_project for that same workspace.\n3. Summarize the project, snapshot, environments, and missing configuration.\nDo not create or start a run yet.`,
  `You are my AI coding agent and QA executor. Process the stored testcase in HoloQA.\n\nUse only the connected remote HoloQA MCP server for HoloQA state. Do not use the dashboard to create, approve, or execute a run. Do not start Docker, uv, Playwright, or a server-side browser worker.\n\n1. Call holoqa_get_requirements for the initialized project.\n2. Confirm that agent-browser is installed locally. If it is missing, stop and ask the user to install it.\n3. Validate the target environment and ask the user to authenticate locally in agent-browser when needed. Never send cookies, tokens, passwords, or storage state to HoloQA.\n4. Call holoqa_create_run_plan, show scope and risks, and ask for approval.\n5. After approval call holoqa_approve_run, then holoqa_open_run_session.\n6. Start the HoloQA live bridge from the client machine using the returned live_endpoint, run_id, and session_token: node scripts/holoqa_agent_bridge.mjs --server <dashboard-origin> --run <run_id> --token <session_token> --session <your-agent-browser-session>. Keep it running while the test executes.\n7. Use agent-browser as the browser executor. Observe the live page before each action and handle cookie banners, modals, redirects, loading states, and changed labels through safe recovery.\n8. Record ordered actions, observations, and recoveries with holoqa_record_agent_event. Send heartbeats with holoqa_agent_heartbeat.\n9. Capture screenshots, DOM, console, HAR/network, and trace evidence locally. Use holoqa_prepare_artifact_upload for every file, upload bytes to the returned Garage URL, then call holoqa_commit_artifact.\n10. Call holoqa_update_case_verdict for every testcase and pass its uploaded artifacts list so the server verifies and attaches them atomically. Use BLOCKED only for a genuine prerequisite or safety stop, not for a recoverable popup or selector mismatch.\n11. Call holoqa_complete_run only after every testcase has a final verdict; it generates and registers the server report artifacts.\nNever expose secrets in messages, events, screenshots, or artifacts.`
]

const steps = [
  { number: '01', title: 'Connect to MCP', icon: TerminalSquare, detail: 'Configure Cursor or Claude to use the Streamable HTTP endpoint exposed by the Docker server. The MCP server and dashboard share one server-side state volume.' },
  { number: '02', title: 'Initialize the project', icon: CircleDot, detail: 'Make the application available to the Docker host under /workspace, then let the AI coder inspect it and create a pinned project snapshot. Local Windows paths are not sent to the remote server.' },
  { number: '03', title: 'Run a testcase', icon: CheckCircle2, detail: 'The AI coder opens a local agent-browser session, authenticates locally, executes the approved intent with recovery, and streams verdicts and Garage-backed evidence to HoloQA. The dashboard only monitors.' },
]

export default function CreateTest() {
  const [endpoint, setEndpoint] = useState(defaultEndpoint)
  const [copied, setCopied] = useState<number | null>(null)
  const prompts = promptsFor(endpoint)
  const copyPrompt = async (index: number) => { await navigator.clipboard.writeText(prompts[index]); setCopied(index); window.setTimeout(() => setCopied(current => current === index ? null : current), 1800) }
  return <FeaturePage eyebrow="Remote agent workflow / start here" title="CREATE A TEST" intro="HoloQA is a monitoring control plane. Your AI coder connects to the Docker-hosted MCP server, owns the test workflow, and sends runs back here for observation." actions={<Link className="button secondary" href="/">Overview <ArrowUpRight className="size-4" /></Link>}>
    <section className="section"><div className="panel"><div className="eyebrow">Required connection</div><div className="flex items-center gap-3" style={{ marginTop: 10 }}><Server className="size-5 text-primary" aria-hidden="true" /><h3 style={{ margin: 0 }}>Remote Streamable HTTP only</h3></div><p className="muted">If HoloQA is missing from the client catalog, the AI coder must ask your confirmation before adding this endpoint or reloading MCP.</p><div className="field" style={{ marginTop: 16, maxWidth: 720 }}><label htmlFor="mcp-endpoint">Remote MCP endpoint</label><input id="mcp-endpoint" value={endpoint} onChange={event => setEndpoint(event.target.value)} placeholder={defaultEndpoint} /></div><div className="callout mono">{endpoint}</div><p className="muted">The application and workbook must be available to the server under <span className="mono">/workspace</span>. A local path such as <span className="mono">C:\workspaces\app</span> is not readable by the remote container.</p></div></section>
    <section className="section grid-3">{steps.map(({ number, title, icon: Icon, detail }) => <article className="panel" key={number}><div className="eyebrow"><span className="index">{number}</span> {title}</div><Icon className="size-5 text-primary" style={{ marginTop: 18 }} aria-hidden="true" /><h3>{title}</h3><p className="muted">{detail}</p></article>)}</section>
    <section className="section"><div className="section-head"><div><div className="eyebrow">Copy-ready handoff</div><h2>Prompts for your AI coder</h2></div><span className="mono muted">REMOTE DOCKER MCP</span></div><div className="create-test-steps">{prompts.map((prompt, index) => <article className="panel" key={index}><div className="flex items-center justify-between gap-3"><h3 style={{ margin: 0 }}>{steps[index].number} / {steps[index].title}</h3><button type="button" className="button secondary inline-flex items-center gap-1.5" onClick={() => copyPrompt(index)}><Copy className="size-3.5" aria-hidden="true" />{copied === index ? 'Copied' : 'Copy prompt'}</button></div><pre className="code-block" style={{ marginTop: 16, whiteSpace: 'pre-wrap', maxHeight: 360, overflow: 'auto' }}>{prompt}</pre></article>)}</div></section>
    <section className="section"><div className="callout"><strong>Platform boundary</strong><br /><span className="muted">HoloQA stores intent, run state, events, and evidence. Your AI coder owns the local browser through agent-browser. Cookies and browser storage stay on the client.</span><br /><Link className="link mono inline-flex items-center gap-1" href="/projects">Open projects <ArrowUpRight className="size-3" /></Link></div></section>
  </FeaturePage>
}
